{{- $root := . }}
{{- if .Values.ingressRoute.enable }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "name" . -}}-ingressroute
  labels:
    {{- include "sk.labels" . | nindent 4}}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 2 }}
  routes:
  - kind: Rule
    match: Host(`{{- .Values.ingressRoute.host -}}`) {{- with .Values.ingressRoute.paths }} && ({{- . | first | printf "PathPrefix(`%s`)" }} 
      {{- range $path := (. | rest) }} || PathPrefix(`{{ $path }}`) {{- end }}) {{- end }}
    services:
      - name: {{ include "name" . | quote }}
        port: {{ .Values.ports.skApp.containerPort }}
        scheme: {{ .Values.ingressRoute.scheme | quote | default "http" }}
        nativeLB: true
  {{- if .Values.ingressRoute.ssl }}
  tls: {}
  {{- end -}}
{{- end -}}
{{- range $ingress := .Values.additionalIngressRoutes }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "name" $root -}}-{{ $ingress.service.name }}-ingressroute
  labels:
    {{- include "sk.labels" $root | nindent 4}}
spec:
  entryPoints:
    {{- toYaml $root.Values.ingressRoute.entryPoints | nindent 2 }}
  routes:
  - kind: Rule
    match: Host(`{{- $ingress.host -}}`) {{- with $ingress.paths }} && ({{- . | first | printf "PathPrefix(`%s`)" }} 
      {{- range $path := (. | rest) }} || PathPrefix(`{{ $path }}`) {{- end }}) {{- end }}
    services:
      - name: {{ $ingress.service.name | quote }}
        port: {{ $ingress.service.port }}
        scheme: {{ $ingress.scheme | quote | default "http" }}
        nativeLB: true
        {{- with $ingress.service.namespace }}
        namespace: {{ . }}
        {{- end }}
  {{- if $root.Values.ingressRoute.ssl }}
  tls: {}
  {{- end -}}
{{- end }}
