{{- if .Values.image.credentials.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sk.registrySecretName" . | quote }}
  labels:
    {{- include "sk.labels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . | quote }}
{{ end -}}